import asyncio
import logging
import random

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Request

from ..dependencies import get_agent_service, get_session_service
from ..models.interview import AnswerRequest, SetupRequest
from ..services.agent_service import AgentService
from ..services.session_service import SessionService

router = APIRouter()
logger = logging.getLogger(__name__)


# ------------------------------------------------------------------
# Setup & Question Generation
# ------------------------------------------------------------------


@router.post("/setup", summary="Create a new interview session and trigger question generation")
async def setup_interview(
    request_body: SetupRequest,
    background_tasks: BackgroundTasks,
    agent_svc: AgentService = Depends(get_agent_service),
    session_svc: SessionService = Depends(get_session_service),
):
    """
    Creates a session and starts the 3-stage question generation pipeline in the background.
    Poll GET /{session_id}/status to know when questions are ready.
    """
    session = await session_svc.create_session(request_body.model_dump())
    session_id = session["session_id"]

    background_tasks.add_task(
        _run_question_generation,
        session_id=session_id,
        setup=request_body.model_dump(),
        agent_svc=agent_svc,
        session_svc=session_svc,
    )

    return {
        "session_id": session_id,
        "status": "generating",
        "message": "Interview session created. Questions are being generated by the AI panel.",
    }


async def _run_question_generation(
    session_id: str,
    setup: dict,
    agent_svc: AgentService,
    session_svc: SessionService,
):
    """
    Background task — parallel question generation pipeline:

      Stage 0  : Company analysis (GPT)
      Stage 1  : GPT generates all 6 initial questions
                 → saved immediately as 'generating' placeholders
      Stage 2-3: TWO parallel pipelines (Claude→Gemini) each refining 3 questions
                 → as each half completes its questions become 'pending'
                 → session becomes 'partial_ready' once first 3 are ready
                 → session becomes 'ready' once all 6 are ready

    The frontend starts showing Q1-3 as soon as 'partial_ready' is set,
    while Q4-6 are still being refined in the background.
    """
    try:
        await session_svc.update_session(session_id, {"status": "generating"})

        # Stage 0: Company analysis
        logger.info("[%s] Analysing company: %s", session_id, setup["company_name"])
        company_analysis = await agent_svc.analyze_company(
            setup["company_name"], setup["interview_type"]
        )
        await session_svc.update_session(session_id, {"company_analysis": company_analysis})

        # Stage 1: GPT generates all 6 questions quickly (~10-20s)
        logger.info("[%s] Stage 1: GPT generating initial questions", session_id)
        initial_6 = await agent_svc._gpt_generate(
            setup["company_name"], setup["job_title"], setup["job_description"],
            setup["years_experience"], setup["interview_type"], company_analysis
        )

        # Pre-assign agents and save GPT drafts as placeholders immediately.
        # Frontend stays on the generating screen but sees progress.
        agents = ["gpt", "gpt", "claude", "claude", "gemini", "gemini"]
        random.shuffle(agents)
        placeholders = [
            {
                "question_id": idx + 1,
                "question": q.get("question", ""),
                "difficulty": q.get("difficulty", "medium"),
                "rationale": q.get("rationale", ""),
                "assigned_agent": agents[idx],
                "answer": None, "evaluations": {}, "consolidated_feedback": None,
                "avg_score": None,
                "status": "generating",  # will become 'pending' after refinement
            }
            for idx, q in enumerate(initial_6[:6])
        ]
        await session_svc.update_session(session_id, {"questions": placeholders})
        logger.info("[%s] GPT drafts saved; starting parallel refinement", session_id)

        # Stages 2-3: Refine each half concurrently; save as each completes
        async def refine_and_save(batch: list, indices: list, label: str):
            refined_half = await agent_svc._refine_half(
                batch,
                setup["company_name"], setup["job_title"], setup["job_description"],
                setup["interview_type"], company_analysis,
            )
            await session_svc.update_question_batch(session_id, indices, refined_half)
            logger.info("[%s] %s complete — questions now pending", session_id, label)

        await asyncio.gather(
            refine_and_save(initial_6[:3], [0, 1, 2], "Batch A (Q1-3)"),
            refine_and_save(initial_6[3:], [3, 4, 5], "Batch B (Q4-6)"),
        )

        await session_svc.update_session(session_id, {"status": "ready"})
        logger.info("[%s] All 6 questions ready", session_id)

    except Exception as exc:
        logger.error("[%s] Question generation failed: %s", session_id, exc, exc_info=True)
        await session_svc.update_session(
            session_id, {"status": "error", "error_message": str(exc)}
        )



# ------------------------------------------------------------------
# Re-attempt
# ------------------------------------------------------------------


@router.post("/{session_id}/reattempt", summary="Re-appear for the same interview with identical questions")
async def create_reattempt(
    session_id: str,
    session_svc: SessionService = Depends(get_session_service),
):
    """
    Creates a new attempt using the exact same questions as the source session.
    All answers and evaluations are cleared. The session starts at 'ready' status —
    no AI generation needed.
    """
    new_session = await session_svc.create_reattempt(session_id)
    if not new_session:
        raise HTTPException(status_code=404, detail="Source session not found")
    return {
        "session_id": new_session["session_id"],
        "attempt_number": new_session["attempt_number"],
        "root_session_id": new_session["root_session_id"],
        "status": new_session["status"],
        "message": (
            f"Attempt #{new_session['attempt_number']} created. "
            "Same questions, fresh evaluation. Good luck!"
        ),
    }


# ------------------------------------------------------------------
# Session Status & Data
# ------------------------------------------------------------------


@router.get("/{session_id}/status", summary="Poll interview session status")
async def get_status(
    session_id: str,
    session_svc: SessionService = Depends(get_session_service),
):
    session = await session_svc.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    return {
        "session_id": session_id,
        "status": session["status"],
        "questions_count": len(session.get("questions", [])),
        "error_message": session.get("error_message"),
    }


@router.get("/{session_id}", summary="Get full interview session")
async def get_interview(
    session_id: str,
    session_svc: SessionService = Depends(get_session_service),
):
    session = await session_svc.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    return session


# ------------------------------------------------------------------
# Answer Submission & Evaluation
# ------------------------------------------------------------------


@router.post("/{session_id}/answer/{question_id}", summary="Submit an answer and trigger evaluation")
async def submit_answer(
    session_id: str,
    question_id: int,
    request_body: AnswerRequest,
    background_tasks: BackgroundTasks,
    agent_svc: AgentService = Depends(get_agent_service),
    session_svc: SessionService = Depends(get_session_service),
):
    """
    Saves the candidate's answer, then runs all-three-agent evaluation in the background.
    Poll GET /{session_id} to see updated evaluations and status.
    """
    session = await session_svc.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    question = next((q for q in session.get("questions", []) if q["question_id"] == question_id), None)
    if not question:
        raise HTTPException(status_code=404, detail="Question not found")

    # Save the answer immediately
    await session_svc.set_question_answer(session_id, question_id, request_body.answer)

    setup = session["setup"]
    background_tasks.add_task(
        _run_evaluation,
        session_id=session_id,
        question_id=question_id,
        question_text=question["question"],
        answer=request_body.answer,
        setup=setup,
        agent_svc=agent_svc,
        session_svc=session_svc,
    )

    return {
        "message": "Answer submitted. Evaluation in progress.",
        "question_id": question_id,
        "status": "evaluating",
    }


async def _run_evaluation(
    session_id: str,
    question_id: int,
    question_text: str,
    answer: str,
    setup: dict,
    agent_svc: AgentService,
    session_svc: SessionService,
):
    try:
        evaluations = await agent_svc.evaluate_answer(
            question=question_text,
            answer=answer,
            company_name=setup["company_name"],
            job_title=setup["job_title"],
            interview_type=setup["interview_type"],
        )
        await session_svc.set_question_evaluations(session_id, question_id, evaluations)
        logger.info("[%s] Q%d evaluated", session_id, question_id)
    except Exception as exc:
        logger.error("[%s] Evaluation for Q%d failed: %s", session_id, question_id, exc, exc_info=True)


# ------------------------------------------------------------------
# Consolidated Feedback
# ------------------------------------------------------------------


@router.post("/{session_id}/feedback/{question_id}", summary="Generate consolidated feedback for a question")
async def get_feedback(
    session_id: str,
    question_id: int,
    agent_svc: AgentService = Depends(get_agent_service),
    session_svc: SessionService = Depends(get_session_service),
):
    session = await session_svc.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    question = next((q for q in session.get("questions", []) if q["question_id"] == question_id), None)
    if not question:
        raise HTTPException(status_code=404, detail="Question not found")

    if question.get("status") != "evaluated":
        raise HTTPException(status_code=400, detail="Answer has not been evaluated yet. Please wait.")

    # Return cached feedback if available
    if question.get("consolidated_feedback"):
        return {"feedback": question["consolidated_feedback"], "avg_score": question.get("avg_score")}

    setup = session["setup"]
    feedback = await agent_svc.generate_consolidated_feedback(
        question=question["question"],
        answer=question.get("answer", ""),
        evaluations=question["evaluations"],
        company_name=setup["company_name"],
        job_title=setup["job_title"],
        interview_type=setup["interview_type"],
    )
    await session_svc.set_consolidated_feedback(session_id, question_id, feedback)

    return {"feedback": feedback, "avg_score": question.get("avg_score")}


# ------------------------------------------------------------------
# Complete Session
# ------------------------------------------------------------------


@router.post("/{session_id}/complete", summary="Complete the session and generate a final report")
async def complete_session(
    session_id: str,
    background_tasks: BackgroundTasks,
    agent_svc: AgentService = Depends(get_agent_service),
    session_svc: SessionService = Depends(get_session_service),
):
    session = await session_svc.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    # Mark any unanswered/pending questions as 'not_attended'
    questions = session.get("questions", [])
    for q in questions:
        if q.get("status") == "pending":
            q["status"] = "not_attended"

    # Calculate overall score from evaluated questions only
    evaluated = [q for q in questions if q.get("status") == "evaluated" and q.get("avg_score") is not None]
    overall_score = (
        round(sum(q["avg_score"] for q in evaluated) / len(evaluated), 1) if evaluated else None
    )

    await session_svc.update_session(
        session_id,
        {"status": "completed", "overall_score": overall_score, "questions": questions},
    )

    # Generate session summary in the background
    background_tasks.add_task(
        _run_summary,
        session_id=session_id,
        agent_svc=agent_svc,
        session_svc=session_svc,
    )

    return {
        "message": "Session completed. Summary is being generated.",
        "session_id": session_id,
        "overall_score": overall_score,
    }


async def _run_summary(session_id: str, agent_svc: AgentService, session_svc: SessionService):
    try:
        session = await session_svc.get_session(session_id)
        if not session:
            return
        summary = await agent_svc.generate_session_summary(session)
        await session_svc.update_session(session_id, {"session_summary": summary})
        logger.info("[%s] Session summary generated", session_id)
    except Exception as exc:
        logger.error("[%s] Summary generation failed: %s", session_id, exc, exc_info=True)


# ------------------------------------------------------------------
# Final Report
# ------------------------------------------------------------------


@router.get("/{session_id}/report", summary="Get the final session report")
async def get_report(
    session_id: str,
    session_svc: SessionService = Depends(get_session_service),
):
    session = await session_svc.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if session.get("status") not in ("completed",):
        raise HTTPException(status_code=400, detail="Session is not completed yet.")
    return session
