import json
import logging
import os
from typing import Dict, Any

from sqlalchemy import create_engine, text
from langchain_anthropic import ChatAnthropic
from langchain_core.tools import tool
from langgraph.prebuilt import create_react_agent
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

DEFAULT_ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-sonnet-4-6").strip() or "claude-sonnet-4-6"

# Global engine registry, maps a session_id to a sqlalchemy engine
_engines: Dict[str, Any] = {}


def get_anthropic_api_key() -> str:
    api_key = os.getenv("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY is not configured. Add it to backend/.env before using chat."
        )
    return api_key

def create_db_url(db_type: str, host: str, port: int, user: str, password: str, db_name: str) -> str:
    """Create a SQLAlchemy connection string."""
    if db_type.lower() == 'postgres':
        return f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db_name}"
    elif db_type.lower() == 'mysql':
        return f"mysql+pymysql://{user}:{password}@{host}:{port}/{db_name}"
    else:
        raise ValueError(f"Unsupported database type: {db_type}")

def set_engine(session_id: str, db_type: str, host: str, port: int, user: str, password: str, db_name: str):
    """Initializes and stores a database engine for the session."""
    url = create_db_url(db_type, host, port, user, password, db_name)
    engine = create_engine(url)
    
    # Test connection
    with engine.connect() as conn:
        conn.execute(text("SELECT 1"))
        
    _engines[session_id] = engine
    return True
    
def get_engine(session_id: str):
    """Retrieve the database engine for a session."""
    if session_id not in _engines:
         raise ValueError(f"No database connection found for session {session_id}. Please configure first.")
    return _engines[session_id]

# --- Tools ---

# We need a way to pass session_id to the tools, but langchain tools don't inherently support dynamic context injected this way easily without complex setup.
# The simplest approach is to require session_id as the first parameter for all DB tools and instruct the LLM to use it.
# However, a cleaner approach is using a class or closure to bind the session_id to the tools at request time.
# Let's use a closure factory for the tools given a session_id.

def create_agent_tools(session_id: str):
    
    @tool
    def execute_sql_query(query: str) -> str:
        """Executes any sql query generated by AI. Get all the data from the database, make sure you append the tables with correct schema."""
        engine = get_engine(session_id)
        try:
            with engine.connect() as conn:
                result = conn.execute(text(query))
                if result.returns_rows:
                    rows = result.fetchall()
                    return json.dumps([dict(row._mapping) for row in rows], default=str)
                else:
                    return f"Query executed successfully. {result.rowcount} rows affected."
        except Exception as e:
            return f"Error executing query: {str(e)}"
            
    @tool
    def get_db_schema_and_tables_list() -> str:
        """Get list of all tables with their schema in the database (Base Tables only)."""
        engine = get_engine(session_id)
        dialect = engine.dialect.name
        
        try:
            if dialect == 'postgresql':
                query = """
                SELECT 
                    table_schema,
                    table_name
                FROM information_schema.tables
                WHERE table_type = 'BASE TABLE'
                    AND table_schema NOT IN ('pg_catalog', 'information_schema')
                ORDER BY table_schema, table_name;
                """
            elif dialect == 'mysql':
                query = """
                SELECT 
                    table_schema,
                    table_name
                FROM information_schema.tables
                WHERE table_type = 'BASE TABLE'
                    AND table_schema NOT IN ('information_schema', 'mysql', 'performance_schema', 'sys')
                ORDER BY table_schema, table_name;
                """
            else:
                 return f"Schema listing not yet fully supported for dialect {dialect}"
                 
            with engine.connect() as conn:
                 result = conn.execute(text(query))
                 rows = result.fetchall()
                 return json.dumps([dict(row._mapping) for row in rows], default=str)
        except Exception as e:
             return f"Error fetching schemas: {str(e)}"

    @tool
    def get_table_definition(table_name: str, schema_name: str) -> str:
        """Get table definition to find all columns, data types, and foreign keys using table_name and schema_name."""
        engine = get_engine(session_id)
        dialect = engine.dialect.name
        
        try:
            if dialect == 'postgresql':
                query = text("""
                select
                 c.column_name,
                 c.data_type,
                 c.is_nullable,
                 c.column_default,
                 tc.constraint_type,
                 ccu.table_name AS referenced_table,
                 ccu.column_name AS referenced_column
                from
                 information_schema.columns c
                LEFT join
                 information_schema.key_column_usage kcu
                 ON c.table_name = kcu.table_name
                 AND c.column_name = kcu.column_name
                LEFT join
                 information_schema.table_constraints tc
                 ON kcu.constraint_name = tc.constraint_name
                 AND tc.constraint_type = 'FOREIGN KEY'
                LEFT join
                 information_schema.constraint_column_usage ccu
                 ON tc.constraint_name = ccu.constraint_name
                where
                 c.table_name = :table_name
                 AND c.table_schema = :schema_name
                order by
                 c.ordinal_position
                """)
            elif dialect == 'mysql':
                query = text("""
                select
                 c.column_name,
                 c.data_type,
                 c.is_nullable,
                 c.column_default,
                 tc.constraint_type,
                 kcu.referenced_table_name AS referenced_table,
                 kcu.referenced_column_name AS referenced_column
                from
                 information_schema.columns c
                LEFT join
                 information_schema.key_column_usage kcu
                 ON c.table_name = kcu.table_name
                 AND c.column_name = kcu.column_name
                 AND c.table_schema = kcu.table_schema
                LEFT join
                 information_schema.table_constraints tc
                 ON kcu.constraint_name = tc.constraint_name
                 AND tc.constraint_type = 'FOREIGN KEY'
                where
                 c.table_name = :table_name
                 AND c.table_schema = :schema_name
                order by
                 c.ordinal_position
                """)
            else:
                 return f"Table definition not yet fully supported for dialect {dialect}"
                 
            with engine.connect() as conn:
                result = conn.execute(query, {"table_name": table_name, "schema_name": schema_name})
                rows = result.fetchall()
                return json.dumps([dict(row._mapping) for row in rows], default=str)
        except Exception as e:
            return f"Error fetching table definition: {str(e)}"
            
    return [execute_sql_query, get_db_schema_and_tables_list, get_table_definition]

def get_agent(session_id: str):
    llm = ChatAnthropic(
        model_name=DEFAULT_ANTHROPIC_MODEL,
        temperature=0,
        api_key=get_anthropic_api_key(),
    )
    tools = create_agent_tools(session_id)
    
    system_prompt = '''You are a DB assistant. You need to run queries in DB aligned with user requests.

Run custom SQL queries to aggregate data and respond to user. Make sure every table has the schema prefix to it in the sql query which you can get from `get_db_schema_and_tables_list` tool.

Fetch all data to analyse it for response if needed. Always double check schema definitions before writing complex queries.'''

    agent_executor = create_react_agent(llm, tools, prompt=system_prompt)
    return agent_executor
